---
alias: "Extended Presence: Restart Stuck Timers"
id: xpresence_stuck_watchdog
description: |
  Every 10 minutes check for presence statues stuck as 'Just Arrived', or 'Just Left'.
  The timer should be 'active', so if it is 'idle', then the status is considered stuck.

trigger:
  # Check every 10 minutes.
  - platform: time_pattern
    minutes: '/10'

variables:
  # Select Active + Idle timers.
  active_timers: "{{ states.timer | selectattr('state','in',['active']) | map(attribute='entity_id') | list }}"
  idle_timers: "{{ states.timer | selectattr('state','in',['idle'])   | map(attribute='entity_id') | list }}"
  # Select "Away" + "Just ..." timers.
  just_state_timers: "{{ states.input_select | selectattr('state','in',['Just Arrived','Just Left']) | map(attribute='entity_id') | join(',') | replace('input_select.','timer.xpresence_') }}"
  away_state_timers: "{{ states.input_select | selectattr('state','in',['Away']) | map(attribute='entity_id') | join(',') | replace('input_select.','timer.xpresence_') }}"
  # Filter away all but the timers in common.
  active_24hr_just_state_timers: "{{ states.timer | selectattr('attributes.duration','in',['23:59:59']) | map(attribute='entity_id') | select('in',active_timers) | select('in',just_state_timers) | list }}"
  idle_away_state_timers: "{{ states.timer | map(attribute='entity_id') | select('in',idle_timers) | select('in',away_state_timers) | list }}"
  idle_just_state_timers: "{{ states.timer | map(attribute='entity_id') | select('in',idle_timers) | select('in',just_state_timers) | list }}"

  # Count the stuck timers.
  stuck_active_count: "{{ active_24hr_just_state_timers|count }}"
  stuck_away_count: "{{ idle_away_state_timers|count }}"
  stuck_just_count: "{{ idle_just_state_timers|count }}"
  stuck_timers_count: "{{ stuck_active_count + stuck_away_count + stuck_just_count }}"

condition:
  # Are there any stuck timers?
  - condition: template
    value_template: '{{ stuck_timers_count|int > 0 }}'

action:
  # Restart the stuck timers.
  - choose:
      - conditions: '{{ stuck_active_count > 0 }}'
        sequence:
          - repeat:
              count: '{{ stuck_active_count }}'
              sequence:
                - service: timer.start
                  data:
                    duration: 00:00:05
                    entity_id: '{{ active_24hr_just_state_timers[repeat.index-1] }}'

  - choose:
      - conditions: '{{ stuck_just_count > 0 }}'
        sequence:
          - repeat:
              count: '{{ stuck_just_count }}'
              sequence:
                - service: timer.start
                  data:
                    duration: 00:00:05
                    entity_id: '{{ idle_just_state_timers[repeat.index-1] }}'

  - choose:
      - conditions: '{{ stuck_away_count > 0 }}'
        sequence:
          - repeat:
              count: '{{ stuck_away_count }}'
              sequence:
                - service: timer.start
                  data:
                    duration: 23:59:59
                    entity_id: '{{ idle_away_state_timers[repeat.index-1] }}'
