---
# Lovelace UI to set a list of irrigation cycle times.
input_text:
  irrigation_zone1_times:
    name: List of times (eg. 08:00,12:00,15:00)
    icon: mdi:clock-outline
  irrigation_zone2_times:
    name: List of times (eg. 11:00,15:30)
    icon: mdi:clock-outline

# Lovelace UI to set the duration of each irrigation cycle.
# input_number:
#   irrigation_zone1_duration:
#     name: Duration in Minutes
#     icon: mdi:timer-sand
#     min: 0
#     max: 60
#     step: 1
#     unit_of_measurement: "minutes"

#   irrigation_zone2_duration:
#     name: Duration in Minutes
#     icon: mdi:timer-sand
#     min: 0
#     max: 60
#     step: 1
#     unit_of_measurement: "minutes"

### Optional offline notifications.
automation:
  # Warn me if the system ever goes offline for more than two hours!
  - alias: Irrigation system offline
    id: irrigation_system_offline
    trigger:
      - platform: state
        entity_id: binary_sensor.irrigation_controller_status
        to: 'off'
        for: '02:00:00'
    action:
      - service: persistent_notification.create
        data:
          title: "Irrigation system offline"
          message: "The Irrigation System has been offline for 2 hours!"
          notification_id: "offline"

      - service: notify.brian
        data:
          title: "Irrigation system offline"
          message: "The Irrigation System has been offline for 2 hours"
