---
# I've adopted Frenck's style of layout. Most automations, components,
# scripts, etc. are broken up into individual files in a logical
# folder structure (e.g. Automations are in /automations,
# components like virtual and actual lights are in /components/lights).
#
# While this may seem excessive I believe this will simplify
# troubleshooting because I will know exactly where to find each button,
# light, and sensors. It is quicker to locate each automation (/automations)
# and script (/scripts) and there won't be any distracting code floating
# around above or below the code I am reviewing.
#
# Look for the following paths:
# * /automations
# * /integration_entities
# * /integrations
# * /scripts
# * /shell_commands
# * /templates
#
# Reference: https://github.com/frenck/home-assistant-config/
#
homeassistant:
  auth_providers: !include_dir_list ./integration_entities/auth_providers

  customize: !include customize.yaml

  packages: !include_dir_named integrations

# lovelace:
#   mode: storage
#   dashboards:
#     sak-examples:
#       mode: yaml
#       filename: ./dashboards/sak-examples-dashboard.yaml
#       title: Swiss Army Knife Examples
#       icon: mdi:hospital-box
#       show_in_sidebar: true
#     sak-tutorials:
#       mode: yaml
#       filename: ./dashboards/sak-tutorials-dashboard.yaml
#       title: Swiss Army Knife Tutorials
#       icon: mdi:hospital-box
#       show_in_sidebar: true
