---
alias: Glowforge announce complete
id: glowforge_announce_complete
trigger:
  - platform: state
    entity_id: input_select.glowforge_status
    to: Complete
action:
  - service: script.notify_speech
    data:
      media_player: group.google_downstairs
      message: "Glowforge is complete!"

  - service: script.notify_mobile
    data:
      title: "Glowforge"
      message: "Glowforge is complete!"
      who: brian
      group: status
      tag: glowforge-status
      url: /lovelace/making

  # - service: script.notify_web
  #   data:
  #     type: success
  #     title: "Glowforge"
  #     message: "Glowforge is complete!"
