---
alias: "Presence: Family Arrival"
id: family_arrival
description: The house will welcome the family member home, after the entry the house via the front or garage entry doors.
mode: single
trigger:
  - platform: state
    entity_id: group.family
    from: not_home
    to: home
    for:
      minutes: 0
      seconds: 5
variables:
  person: '{{ trigger.to_state.object_id }}'
  old_state: '{{ trigger.from_state.state }}'
  xpresence_states:
    not_home: Away
    home: Home
  previous_state: '{{ xpresence_states[old_state] }}'
condition:
  # Only make an announcement if the person has been Away.
  - condition: template
    value_template: '{{ previous_state == "Away" }}'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.away_mode

  - alias: "Wait for an entry door to open before making the announcement."
    wait_for_trigger:
      platform: state
      entity_id:
        - binary_sensor.front_door
        - binary_sensor.garage_entry_door
      from: "off"
      to: "on"
    timeout:
      minutes: "5"
    continue_on_timeout: false

  - alias: "House welcomes you home!"
    service: script.say
    data_template:
      media_player: group.google_welcome
      person_arriving: "{{ trigger.entity_id.split('.')[1]|title|replace('_', ' ') }}"
      say_greeting: "true"
      say_inside_weather: "true"
      say_outside_weather: "true"
      #say_door_window_check: "true"
      #say_light_check: "true"
      #say_plant_problems: "true"
