---
unique_id: docker_pi_zigbee2mqtt
platform: rest
name: Docker pi01 zigbee
icon: mdi:docker
resource: http://10.0.0.200:8126/container/smarthome-zigbee
value_template: '{{ value_json is not none and value_json.state == "running" }}'
