---
alias: Safety alert smoke or carbon monoxide
id: safety_alert_smoke
mode: single
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.safety_alarm_bedroom_type
      - sensor.safety_alarm_kyles_bedroom_type
      - sensor.safety_alarm_lucas_bedroom_type
      - sensor.safety_alarm_garage_type
      - sensor.safety_alarm_goez_suite_type
      - sensor.safety_alarm_guest_room_type
      - sensor.safety_alarm_stairs_type

      #- sensor.safety_alarm_test_type
    above: 0
    below: 13

variables:
  type: '{{ trigger.to_state.state|default(0)|int }}'
  room: '{{ trigger.to_state.name|replace(":","")|replace("Safety alarm ","")|replace(" type","") }}'

  alarm_states:
    1: "SMOKE"
    2: "CARBON MONOXIDE"
    12: "Test button press"
  alarm_state: '{{ alarm_states[type]|upper if type in alarm_states.keys() else "unknown" }}'

  title: '{{ alarm_state }} DETECTED!'
  message: '{{ alarm_state }} detected in the {{ room|upper }}.'

condition:
  # Ignore unknown states as these can occur when the Z-wave docker restarts.
  - condition: template
    value_template: '{{ type in [1,2,12] }}'

action:
  - service: script.notify_mobile
    data:
      critical: true
      title: '{{ title }}'
      message: '{{ message }}'
      who: brian
      group: safety
      url: /lovelace/home

  - service: script.notify_speech
    data:
      media_player: group.google_downstairs
      message: '{{ message }}'

  - service: script.notify_web
    data:
      type: alert
      title: '{{ title }}'
      message: '{{ message }}'
  
  - service: script.notify_persistent
    data:
      title: '{{ title }}'
      message: '{{ message }}'
      id: '{{ "safety_alert_" ~ as_timestamp(now()) }}'

  # Cool down timer. When "mode: single" this stops this automation from running more often than this.
  #- delay:
  #    minutes: 5
