---
alias: Safety alert leak
id: safety_alert_leak
mode: single
trigger:
  platform: state
  entity_id:
    - binary_sensor.dishwasher_leak
    - binary_sensor.downstairs_bathroom_leak
    - binary_sensor.garage_water_heater_leak
    - binary_sensor.goez_suite_bathroom_1_leak
    - binary_sensor.goez_suite_bathroom_2_leak
    - binary_sensor.goez_suite_water_heater_leak
    - binary_sensor.kitchen_leak
    - binary_sensor.master_bathroom_1_leak
    - binary_sensor.master_bathroom_2_leak
    - binary_sensor.upstairs_bathroom_leak
  from: "off"
  to: "on"
condition:
  - condition: template
    value_template: '{{ trigger.to_state.name|trim != "" }}'
variables:
  room: '{{ trigger.to_state.name|lower|replace(" leak", "")|replace(" #1", "")|replace(" #2", "")|trim }}'
  title: 'WATER LEAK DETECTED!'
  message: 'WATER LEAK detected in the {{ room|upper }}.'
action:
  - service: script.notify_speech
    data:
      media_player: group.google_speakers
      message: "A leak has been detected in the {{ room }}!"

  - service: script.notify_mobile
    data:
      critical: true
      title: "{{ title }}"
      message: "{{ message }}"
      who: brian
      group: safety
      url: /lovelace/home

  - service: script.notify_web
    data:
      type: alert
      title: "{{ title }}"
      message: "{{ message }}"

  - service: script.notify_persistent
    data:
      title: '{{ title }}'
      message: '{{ message }}'
      id: '{{ "safety_alert_" ~ as_timestamp(now()) }}'

  # Cool down timer. When "mode: single" this stops this automation from running more often than this.
  - delay:
      minutes: 5
