---
alias: "Toggle Table Lamp"
initial_state: on
trigger:
  platform: webhook
  webhook_id: light_toggle
action:
  - service: light.toggle
    entity_id: light.family_room_table_lamp
    #entity_id: >
    #  {{ trigger.payload_json.entity_id }}
    #entity_id: "{{ trigger.payload }}"