---
alias: feed_notificaitons
initial_state: true
trigger:
  platform: event
  event_type: feedreader
action:
  - service: persistent_notification.create
    data_template:
      title: "{{ trigger.event.data.title }}"
      message: "[{{ trigger.event.data.title }}]({{ trigger.event.data.link }})"
      notification_id: "rss"
