---
# Lock the front door and close the garage door when Brian charges his phone at night.
alias: Safety Alert Lock Door At Bedtime
id: safety_alert_lock_door_at_bedtime
trigger:
  # When Brian's phone is charging.
  - platform: state
    entity_id: device_tracker.life360_brian
    attribute: battery_charging
    to: "true"
condition:
  condition: and
  conditions:
    # Only during night time
    - condition: time
      after: "20:00"
      before: "6:00"
    # and only if Brian or Nerene are home.
    - condition: or
      conditions:
        - condition: state
          entity_id:
            - person.brian
            - person.nerene
          state: 'home'
action:
  - alias: "Lock the front door, if it was left unlocked."
    choose:
      - conditions:
        - condition: state
          entity_id: lock.front_door
          state: "unlocked"
        sequence:
          - service: lock.lock
            entity_id: lock.front_door

  - alias: "Close the garage door, if it was left open."
    choose:
      - conditions:
        - condition: state
          entity_id: cover.garage_door
          state: "open"
        sequence:
          - service: cover.close_cover
            entity_id: cover.garage_door
