---
alias: youtube_notifications
initial_state: true
trigger:
  - platform: state
    entity_id: sensor.drzzs
    attribute: url
  - platform: state
    entity_id: sensor.franck_nijhof
    attribute: url
  - platform: state
    entity_id: sensor.the_hook_up
    attribute: url
action:
  - service: persistent_notification.create
    data_template:
      title: "YouTube: {{ trigger.to_state.attributes.friendly_name }}"
      message: >-
        {{ trigger.to_state.state }}
        {{ trigger.to_state.attributes.url }}
      notification_id: "youtube"

  - service: script.notify_mobile
    data_template:
      title: "YouTube: {{ trigger.to_state.attributes.friendly_name }}"
      message: "{{ trigger.to_state.state }}"
      image: "{{ trigger.to_state.attributes.entity_picture }}"
      url: "{{ trigger.to_state.attributes.url }}"
      who: "brian"
