---
alias: "Printer: Turn off when idle"
id: printer_turn_off_when_idle
initial_state: true
mode: restart # Restart when the state changes.
trigger:
  - platform: state
    entity_id: sensor.hp_colorlaserjet
    to: "idle"
    for:
      minutes: 15
action:
  - service: switch.turn_off
    entity_id: switch.printers
