---
alias: Holiday Colors Apply
id: holiday_colors_apply
description: Apply the light colors assigned to the current holiday.
trigger:
  - platform: state
    entity_id:
      - light.porch
      - light.table_lamp
    from: "off"
    to: "on"
variables:
  holiday: '{{ states('sensor.holiday') }}'
condition:
  # Only continue if there is a holiday scene to apply.
  - condition: template
    value_template: "{{ holiday|lower not in ['','unavailable'] }}"
action:
  - service: script.holiday_color_change
