---
##############################################
## Adjust brightness of each light as it is
## turned on.
##############################################
alias: lights_adjust_as_turned_on
initial_state: false
trigger:
  - platform: event
    event_type: state_changed
condition:
  # Only look at lights.
  - condition: template
    value_template: "{{ trigger.event.data is not none
                    and trigger.event.data.entity_id is not none
                    and 'light' in trigger.event.data.entity_id|lower }}"
  # Only when lights are going from off to on.
  - condition: template
    value_template: "{{ trigger.event.data.old_state.state == 'off'
                    and trigger.event.data.new_state.state == 'on' }}"
action:
  - service: script.lights_by_time
    data_template:
      entity: >
        {{ trigger.event.data.entity_id }}
