---
##############################################
## Turn certain lights off after sunrise
##############################################
alias: Sunrise Lights
id: sunrise_lights

trigger:
  - platform: sun
    event: sunrise
    offset: '+0:30:00'
action:
  # Turn off the night time lights.
  - service: light.turn_off
    data:
      entity_id:
        - light.home_entry
        - light.porch
      transition: 5
