---
alias: Kitchen Presence on State Change
id: kitchen_presence_on_state_change
mode: restart
trigger:
  # Use motion because presence is too slow and light will stay on far too long.
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: binary_sensor.kitchen_1_motion
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: binary_sensor.kitchen_2_motion
variables:
  old_state: '{{ trigger.event.data.old_state.state }}'
  new_state: '{{ trigger.event.data.new_state.state }}'

  both_motion_off: '{{ states("binary_sensor.kitchen_1_motion") == "off" and states("binary_sensor.kitchen_2_motion") == "off" }}'
condition:
  - '{{ (new_state in ["off","on"] and old_state in ["off","on"])
      and old_state != new_state }}'
action:
  # - service: script.debug
  #   data:
  #     title: '{{ old_state }} -> {{ new_state }}'
  #     message: '{{ trigger.event.data }}'

  - choose:
      # Motion or presence turns lights on.
      - conditions: '{{ new_state == "on" }}'
        sequence:
          - service: light.turn_on
            entity_id: light.kitchen_cabinet

      # Presence timeout turns lights off.
      - conditions: '{{ new_state == "off" and both_motion_off|lower == "true" }}'
        sequence:
          - service: light.turn_off
            entity_id: light.kitchen_cabinet
