---
platform: rest
name: Docker wyze bridge
resource: http://10.0.0.4:8126/container/docker-wyze-bridge
body_on: '{"state": "start"}'
body_off: '{"state": "stop"}'
is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
