---
alias: watchdog_school_travel_time_alert
initial_state: True
trigger:
  - platform: numeric_state
    entity_id: sensor.waze_travel_time
    above: 15
action:
  - service: script.notify_ios
    data_template:
      title: "Traffic warning"
      message: "It would take {{ states.sensor.waze_travel_time.state }} minutes to get to school if we left now."

  - service: script.notify_speech
    data_template:
      media_player: >-
        "media_player.kitchen"
      message: "Traffic is heavy this morning. It would take {{ states.sensor.waze_travel_time.state }} minutes to get to school if we left now."