---
alias: front_door_unlocked_timer_restart
id: front_door_unlocked_timer_restart
mode: single
# When the front door is opened, restart the timer.
trigger:
  - platform: state
    entity_id: binary_sensor.front_door
    to: "on"
condition:
  # Only restart the countdown timer when both Guest Mode and Leave Unlocked Mode are disabled.
  condition: and
  conditions:
    - condition: state
      entity_id:
        - input_boolean.guest_mode
        - input_boolean.leave_unlocked
      state: "off"
action:
  - alias: "Cancel the existing lock countdown timer."
    service: timer.cancel
    target:
      entity_id: timer.front_door_unlocked

  - alias: "Restart the lock countdown timer."
    service: timer.start
    target:
      entity_id: timer.front_door_unlocked
