---
alias: Front Door Open State
id: front_door_opened
mode: single
trigger:
  - id: door_open
    platform: state
    entity_id: binary_sensor.front_door
    from: "off"
    to: "on"
  - id: door_closed
    platform: state
    entity_id: binary_sensor.front_door
    from: "on"
    to: "off"
condition:
  alias: "Only start the lock countdown when certain modes are disabled."
  condition: and
  conditions:
    - condition: state
      entity_id:
        - input_boolean.guest_mode
        - input_boolean.leave_unlocked
      state: "off"
action:
  - choose:
    - alias: "Cancel the unlocked countdown timer when front door is opened."
      conditions:
        - '{{ trigger.id == "door_open" }}'
      sequence:
        - alias: "First pause the timer."
          service: timer.pause
          target:
            entity_id: timer.front_door_unlocked

        - alias: "Now cancel the timer."
          service: timer.cancel
          target:
            entity_id: timer.front_door_unlocked


    - alias: "Start the unlocked countdown timer when front door is closed."
      conditions:
        - '{{ trigger.id == "door_closed" }}'
      sequence:
        - alias: "Restart the timer."
          service: timer.start
          target:
            entity_id: timer.front_door_unlocked
