---
alias: Open/close house a/c change
description: Actions to take when the alert has been cleared.
mode: single
trigger:
  # - id: close_house_complete
  #   platform: state
  #   entity_id: alert.close_house
  #   from: "on"
  #   to: "idle"
  - id: house_closed
    platform: template
    value_template: |
      {{
        is_state("binary_sensor.house_windows","off") and
        is_state("binary_sensor.sliding_door","off")
      }}

  - id: open_house_complete
    platform: state
    entity_id: alert.open_house
    from: "on"
    to: "idle"
  - id: windows_open
    platform: state
    entity_id: binary_sensor.house_windows
    from: "off"
    to: "on"
    for:
      seconds: 30
  - id: sliding_door_open
    platform: state
    entity_id: binary_sensor.sliding_door
    from: "off"
    to: "on"
    for:
      minutes: 1
action:
  - if:
      - condition: and
        conditions:
          - condition: template
            value_template: '{{ is_state("climate.home_thermostat","off") }}'
          - condition: or
            conditions:
              - condition: trigger
                id: house_closed
              - condition: trigger
                id: close_house_complete
    then:
      - service: climate.set_temperature
        target:
          entity_id: climate.home_thermostat
        data:
          hvac_mode: cool
          temperature: 77

    else:
      - service: climate.turn_off
        target:
          entity_id: climate.home_thermostat
