---
alias: Dryer status update
id: dryer_status_update
description: Update the current dryer status when certain criteria are met.
mode: single
trigger:
  - platform: state
    entity_id: sensor.dryer_power_monitor_power

  - id: from_drying_to_dry
    platform: state
    entity_id: input_select.dryer_status
    from: "Drying"
    to: "Dry"
variables:
  trigger_id: '{{ trigger.id }}'
  power: '{{ states("sensor.dryer_power_monitor_power")|int(default=0) }}'
  previous_status: '{{ states("input_select.dryer_status") }}'
  status: |
    {% if power > 150 %}
      Drying
    {%- elif previous_status == "Drying" %}
      Dry
    {%- endif %}
condition:
  - condition: template
    value_template: '{{ status != previous_status }}'
action:
  - service: input_select.select_option
    target:
      entity_id: input_select.dryer_status
    data:
      option: '{{ status }}'

  - alias: 'Start the "Off" timer.'
    if:
      - condition: template
        value_template: '{{
            trigger_id == "from_drying_to_dry" or
            (previous_status == "Drying" and status == "Dry")
          }}'
    then:
      - service: timer.cancel
        target:
          entity_id: timer.dryer_dry
      - service: timer.start
        target:
          entity_id: timer.dryer_dry
