---
alias: Bedroom a/c sync power state
id: bedroom_ac_sync_power_state
description: "Using power monitoring to update the Sensibo device when the A/C state is changed at the control panel."
mode: restart
trigger:
  - id: "cool"
    platform: numeric_state
    entity_id: sensor.bedroom_ac_power
    above: 100
    for:
      seconds: 10
    variables:
      powered_state: "on"
  # - id: "fan_only"
  #   platform: numeric_state
  #   entity_id: sensor.bedroom_ac_power
  #   above: 10
  #   for:
  #     seconds: 10
  - id: "off"
    platform: numeric_state
    entity_id: sensor.bedroom_ac_power
    below: 10
    for:
      minutes: 15
    variables:
      powered_state: "off"
variables:
  # hvac_modes: off, cool, fan_only, dry, heat_cool
  assumed_state: '{{ states("climate.bedroom_thermostat") }}'

  # power: '{{ states("sensor.bedroom_ac_power")|int(default=0) }}'
  # powered_state: |
  #   {% if power < 10 %}
  #     off
  #   {%- else %}
  #     cool
  #   {%- endif %}
condition:
  - condition: template
    value_template: '{{ powered_state != assumed_state }}'
action:
  - service: sensibo.assume_state
    target:
      entity_id: climate.bedroom_thermostat
    data:
      state: '{{ powered_state }}'
