# Source: https://github.com/BeardedTinker/Home-Assistant_Config/blob/master/entities/sensors/system/count_lines.yaml
---
sensor:
  unique_id: devices_active_count
  name: Devices active count
  command: |
    cat /config/.storage/core.device_registry | grep 'deleted_devices' -B 100000 | grep -c '"config_entries": '
  command_timeout: 120
  value_template: "{{ value }}"
